spring:
  cloud:
    stream:
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0 :
          destination: payment-event
    function:
      definition: orderSupplier;paymentEventConsumer


server:
  port: 8081